CIRCUITPY_WIFI_SSID="ssid"
CIRCUITPY_WIFI_PASSWORD="password"

CIRCUITPY_WIFI_FALLBACK_SSID="ssid"
CIRCUITPY_WIFI_FALLBACK_PASSWORD="password"

CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_API_PASSWORD="picopad"
